/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "author";
  };
  mainImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  categories?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "category";
  }>;
  publishedAt?: string;
  body?: BlockContent;
};

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
  listItem?: "bullet";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
} | {
  asset?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
  };
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: "image";
  _key: string;
}>;

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type MediaTag = {
  _id: string;
  _type: "media.tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = Post | BlockContent | SanityImageCrop | SanityImageHotspot | Author | Slug | Category | MediaTag | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/sanity/queries/article.ts
// Variable: postsQuery
// Query: *[_type == "post"] | order(publishedAt desc) {    _id,    title,    slug,    publishedAt,    "author": author-> {      name,      "image": image.asset->url    },    "mainImage": {      "url": mainImage.asset->url,      "alt": mainImage.alt    },    "categories": categories[]-> {      _id,      title,      slug    },    body  }
export type PostsQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  publishedAt: string | null;
  author: {
    name: string | null;
    image: string | null;
  } | null;
  mainImage: {
    url: string | null;
    alt: string | null;
  };
  categories: Array<{
    _id: string;
    title: string | null;
    slug: Slug | null;
  }> | null;
  body: BlockContent | null;
}>;
// Variable: singlePostQuery
// Query: *[_type == "post" && slug.current == $slug][0] {    _id,    title,    slug,    publishedAt,    "author": author-> {      name,      "image": image.asset->url    },    "mainImage": {      "url": mainImage.asset->url,      "alt": mainImage.alt    },    "categories": categories[]-> {      _id,      title,      slug    },    body  }
export type SinglePostQueryResult = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  publishedAt: string | null;
  author: {
    name: string | null;
    image: string | null;
  } | null;
  mainImage: {
    url: string | null;
    alt: string | null;
  };
  categories: Array<{
    _id: string;
    title: string | null;
    slug: Slug | null;
  }> | null;
  body: BlockContent | null;
} | null;
// Variable: postsByCategoryQuery
// Query: *[_type == "post" && $categorySlug in categories[]->slug.current] | order(publishedAt desc) {    _id,    title,    slug,    publishedAt,    "author": author-> {      name,      "image": image.asset->url    },    "mainImage": {      "url": mainImage.asset->url,      "alt": mainImage.alt    },    "categories": categories[]-> {      _id,      title,      slug    },    body  }
export type PostsByCategoryQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  publishedAt: string | null;
  author: {
    name: string | null;
    image: string | null;
  } | null;
  mainImage: {
    url: string | null;
    alt: string | null;
  };
  categories: Array<{
    _id: string;
    title: string | null;
    slug: Slug | null;
  }> | null;
  body: BlockContent | null;
}>;
// Variable: categoriesQuery
// Query: *[_type == "category"] | order(title asc) {    _id,    title,    slug  }
export type CategoriesQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n  *[_type == \"post\"] | order(publishedAt desc) {\n    _id,\n    title,\n    slug,\n    publishedAt,\n    \"author\": author-> {\n      name,\n      \"image\": image.asset->url\n    },\n    \"mainImage\": {\n      \"url\": mainImage.asset->url,\n      \"alt\": mainImage.alt\n    },\n    \"categories\": categories[]-> {\n      _id,\n      title,\n      slug\n    },\n    body\n  }\n": PostsQueryResult;
    "\n  *[_type == \"post\" && slug.current == $slug][0] {\n    _id,\n    title,\n    slug,\n    publishedAt,\n    \"author\": author-> {\n      name,\n      \"image\": image.asset->url\n    },\n    \"mainImage\": {\n      \"url\": mainImage.asset->url,\n      \"alt\": mainImage.alt\n    },\n    \"categories\": categories[]-> {\n      _id,\n      title,\n      slug\n    },\n    body\n  }\n": SinglePostQueryResult;
    "\n  *[_type == \"post\" && $categorySlug in categories[]->slug.current] | order(publishedAt desc) {\n    _id,\n    title,\n    slug,\n    publishedAt,\n    \"author\": author-> {\n      name,\n      \"image\": image.asset->url\n    },\n    \"mainImage\": {\n      \"url\": mainImage.asset->url,\n      \"alt\": mainImage.alt\n    },\n    \"categories\": categories[]-> {\n      _id,\n      title,\n      slug\n    },\n    body\n  }\n": PostsByCategoryQueryResult;
    "\n  *[_type == \"category\"] | order(title asc) {\n    _id,\n    title,\n    slug\n  }\n": CategoriesQueryResult;
  }
}
